[package]
description = "Authenticated node-to-node HTTP/2 pools for Nervix clusters"
edition.workspace = true
license-file.workspace = true
name = "nervix-interconnect"
version.workspace = true

[lints]
workspace = true

[features]
default = []
shuttle = [
  "dep:shuttle",
  "nervix-execution/shuttle",
  "dep:shuttle-dashmap",
  "dep:shuttle-parking-lot",
  "dep:shuttle-tokio",
  "dep:shuttle-tokio-util",
  "shuttle-dashmap/shuttle",
  "shuttle-parking-lot/shuttle",
  "shuttle-tokio/shuttle",
  "shuttle-tokio-util/shuttle",
]

[dependencies]
ahash = { workspace = true }
arch-into = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
error-stack = { workspace = true }
fastrand = { workspace = true }
futures-util = { workspace = true }
h2 = { workspace = true }
http = { workspace = true }
meticulous = { workspace = true }
nervix-execution = { workspace = true }
nervix-models = { workspace = true }
nervix-recovery = { workspace = true }
parking_lot = { workspace = true }
percent-encoding = { workspace = true }
rand_core = { workspace = true }
rkyv = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
shuttle = { workspace = true, optional = true }
shuttle-dashmap = { workspace = true, optional = true }
shuttle-parking-lot = { workspace = true, optional = true }
shuttle-tokio = { workspace = true, features = ["full"], optional = true }
shuttle-tokio-util = { workspace = true, features = ["rt"], optional = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
triomphe = { workspace = true }
url = { workspace = true }
x509-parser = { workspace = true }

[dev-dependencies]
alloc_count = { workspace = true }
rcgen = { workspace = true }
tempfile = { workspace = true }
ubyte = { workspace = true }
