//! The named concepts of the domain, one type each, generated from one shape.
//!
//! A name owns its validation. `RelayName::parse` is the only way to obtain a `RelayName`, so
//! every holder of one already knows it is non-empty, within the length bound, spelled from the
//! permitted alphabet, and normalised to lower case. Code downstream of construction never
//! re-checks any of that, and a relay name cannot be passed where a schema name is meant.
//!
//! Every name type is generated by [`declare_names!`], so they share exactly one shape:
//! construction, normalisation, comparison, ordering, hashing, display, serde, and the archived
//! form. Their immutable text is reference counted, so cloning a name or widening it to a
//! [`ModelName`] does not copy the text. The only thing a declaration chooses is whether a dot
//! belongs to the name's alphabet.

use std::{
    borrow::Borrow,
    cmp::Ordering,
    fmt::{Debug, Display, Formatter},
    hash::{Hash, Hasher},
    str::FromStr,
};

use error_stack::Report;
use rkyv::{
    Archive, Deserialize as RkyvDeserialize, Place, Serialize as RkyvSerialize, SerializeUnsized,
    rancor::{Fallible, Source},
    string::{ArchivedString, StringResolver},
};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use triomphe::Arc;

/// The longest a name may be, in bytes.
const MAX_NAME_LEN: usize = 128;

/// Why a string is not a name.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum NameError {
    #[error("name must not be empty")]
    Empty,
    #[error("name length {actual} exceeds max length {max}")]
    TooLong { max: usize, actual: usize },
    #[error("invalid character '{ch}' in name")]
    InvalidChar { ch: char },
    #[error("dot '.' is not allowed")]
    DotNotAllowed,
}

/// Whether a dot belongs to a name's alphabet.
///
/// A domain is one segment and never contains a dot, which is what lets a qualified name be split
/// on its first dot without ambiguity. Every other name may carry one, because external systems
/// name topics, tables, and subjects that way.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DotPolicy {
    Allowed,
    Rejected,
}

/// Immutable text shared by every clone and typed view of one name.
#[derive(Debug, Clone)]
pub struct NameText {
    text: Arc<String>,
}

impl NameText {
    #[inline]
    fn as_str(&self) -> &str {
        &self.text
    }

    #[cfg(test)]
    fn shares_allocation_with(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.text, &other.text)
    }
}

impl PartialEq for NameText {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.text, &other.text) || self.as_str() == other.as_str()
    }
}

impl Eq for NameText {}

impl PartialOrd for NameText {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for NameText {
    #[inline]
    fn cmp(&self, other: &Self) -> Ordering {
        if Arc::ptr_eq(&self.text, &other.text) {
            Ordering::Equal
        } else {
            self.as_str().cmp(other.as_str())
        }
    }
}

impl Hash for NameText {
    #[inline]
    fn hash<H>(&self, state: &mut H)
    where
        H: Hasher,
    {
        self.as_str().hash(state);
    }
}

impl From<String> for NameText {
    fn from(value: String) -> Self {
        Self {
            text: Arc::new(value),
        }
    }
}

impl Serialize for NameText {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for NameText {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Ok(value.into())
    }
}

impl Archive for NameText {
    type Archived = ArchivedString;
    type Resolver = StringResolver;

    fn resolve(&self, resolver: Self::Resolver, out: Place<Self::Archived>) {
        ArchivedString::resolve_from_str(self.as_str(), resolver, out);
    }
}

impl<S> RkyvSerialize<S> for NameText
where
    S: Fallible + ?Sized,
    S::Error: Source,
    str: SerializeUnsized<S>,
{
    fn serialize(&self, serializer: &mut S) -> Result<Self::Resolver, S::Error> {
        ArchivedString::serialize_from_str(self.as_str(), serializer)
    }
}

impl<D> RkyvDeserialize<NameText, D> for ArchivedString
where
    D: Fallible + ?Sized,
{
    fn deserialize(&self, _: &mut D) -> Result<NameText, D::Error> {
        Ok(self.as_str().to_string().into())
    }
}

/// Generate the shared shape of a named domain concept.
///
/// Each entry declares one name type and the only thing that varies between them: whether a dot
/// is part of its alphabet. Everything else — the newtype, construction through validation,
/// borrowing as a `str`, comparison, ordering, hashing, display, serde, and the archived form —
/// is generated identically, so no name type can drift from the others.
macro_rules! declare_names {
    ($($(#[$doc:meta])* $Name:ident => $dots:ident,)+) => {
        $(
            $(#[$doc])*
            #[derive(
                Clone,
                PartialEq,
                Eq,
                PartialOrd,
                Ord,
                Hash,
                Serialize,
                Deserialize,
                Archive,
                RkyvSerialize,
                RkyvDeserialize,
            )]
            #[rkyv(derive(PartialEq, Eq, PartialOrd, Ord, Hash))]
            pub struct $Name(NameText);

            impl Debug for $Name {
                fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
                    f.debug_tuple(stringify!($Name))
                        .field(&self.as_str())
                        .finish()
                }
            }

            impl $Name {
                /// Whether this name may contain a dot.
                pub const DOTS: DotPolicy = DotPolicy::$dots;

                /// Validate and normalise `raw` into a name of this kind.
                pub fn parse(raw: &str) -> Result<Self, Report<NameError>> {
                    let name = validate(raw, Self::DOTS)?;
                    Ok(Self(name.into()))
                }

                #[inline]
                pub fn as_str(&self) -> &str {
                    self.0.as_str()
                }
            }

            impl TryFrom<&str> for $Name {
                type Error = NameError;

                fn try_from(value: &str) -> Result<Self, Self::Error> {
                    Self::parse(value).map_err(|report| report.current_context().clone())
                }
            }

            impl TryFrom<String> for $Name {
                type Error = NameError;

                fn try_from(value: String) -> Result<Self, Self::Error> {
                    Self::try_from(value.as_str())
                }
            }

            impl FromStr for $Name {
                type Err = NameError;

                fn from_str(value: &str) -> Result<Self, Self::Err> {
                    Self::try_from(value)
                }
            }

            impl AsRef<str> for $Name {
                #[inline]
                fn as_ref(&self) -> &str {
                    self.0.as_str()
                }
            }

            impl Borrow<str> for $Name {
                #[inline]
                fn borrow(&self) -> &str {
                    self.0.as_str()
                }
            }

            impl Display for $Name {
                #[inline]
                fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
                    f.write_str(self.0.as_str())
                }
            }
        )+
    };
}

declare_names! {
    /// A domain: the owner of every other named concept.
    DomainName => Rejected,

    /// A schema declared with `CREATE SCHEMA`.
    SchemaName => Allowed,
    /// A wire schema declared with `CREATE JSON`, `CBOR`, or `AVRO WIRE SCHEMA`.
    WireSchemaName => Allowed,
    /// A codec declared with `CREATE CODEC`.
    CodecName => Allowed,
    /// A connector client declared with `CREATE CLIENT`.
    ClientName => Allowed,
    /// A virtual host declared with `CREATE VHOST`.
    VhostName => Allowed,
    /// A branch declared with `CREATE BRANCH`.
    BranchName => Allowed,
    /// A listening endpoint declared with `CREATE ENDPOINT`.
    EndpointName => Allowed,
    /// A signaling protocol declared with `CREATE SIGNALING PROTOCOL`.
    SignalingProtocolName => Allowed,
    /// A generator declared with `CREATE GENERATOR`.
    GeneratorName => Allowed,
    /// An inferencer declared with `CREATE INFERENCER`.
    InferencerName => Allowed,
    /// A WASM processor declared with `CREATE WASM PROCESSOR`.
    WasmProcessorName => Allowed,
    /// An ingestor declared with `CREATE INGESTOR`.
    IngestorName => Allowed,
    /// A reingestor declared with `CREATE REINGESTOR`.
    ReingestorName => Allowed,
    /// A relay declared with `CREATE RELAY`.
    RelayName => Allowed,
    /// A lookup declared with `CREATE LOOKUP`.
    LookupName => Allowed,
    /// A junction declared with `CREATE JUNCTION`.
    JunctionName => Allowed,
    /// A deduplicator declared with `CREATE DEDUPLICATOR`.
    DeduplicatorName => Allowed,
    /// A correlator declared with `CREATE CORRELATOR`.
    CorrelatorName => Allowed,
    /// A reorderer declared with `CREATE REORDERER`.
    ReordererName => Allowed,
    /// A window processor declared with `CREATE WINDOW PROCESSOR`.
    WindowProcessorName => Allowed,
    /// An emitter declared with `CREATE EMITTER`.
    EmitterName => Allowed,
    /// A placement declared with `CREATE PLACEMENT`.
    PlacementName => Allowed,
    /// A user-defined function declared with `CREATE UDF`.
    UdfName => Allowed,

    /// The name of a control-plane entity, held next to the kind that says what it names. Storage
    /// keys, `DROP`, `SHOW CREATE`, placement members, relocation members, and diagnostics all
    /// address an entity this way, because the kind is carried beside the name rather than in it.
    ModelName => Allowed,

    /// An uploaded resource, addressed by name and version.
    ResourceName => Allowed,
    /// A user declared with `CREATE USER`.
    UserName => Allowed,
    /// A session subscription created over a client session.
    SubscriptionName => Allowed,
    /// A field of a schema, wire schema, or UDF argument list.
    FieldName => Allowed,
    /// A built-in function called from an expression.
    BuiltinFunctionName => Allowed,
    /// A node of the Nervix cluster.
    ClusterNodeName => Allowed,

    /// A topic of an external broker.
    TopicName => Allowed,
    /// A queue of an external broker.
    QueueName => Allowed,
    /// A NATS queue group.
    QueueGroupName => Allowed,
    /// A channel of an external broker.
    ChannelName => Allowed,
    /// A NATS subject.
    SubjectName => Allowed,
    /// A table of an external database or catalog.
    TableName => Allowed,
    /// A collection of an external document database.
    CollectionName => Allowed,
    /// A Kafka consumer group.
    ConsumerGroupName => Allowed,
    /// A Pulsar subscription.
    PulsarSubscriptionName => Allowed,
}

/// Generate the widening of an entity's own name into the kind-erased [`ModelName`].
///
/// Only the names of control-plane entities widen. A field, a topic, or a cluster node does not
/// name an entity, so it has no `ModelName` form and cannot become a storage key by accident.
macro_rules! declare_model_names {
    ($($Name:ident,)+) => {
        $(
            impl From<$Name> for ModelName {
                #[inline]
                fn from(name: $Name) -> Self {
                    Self(name.0)
                }
            }

            impl From<&$Name> for ModelName {
                #[inline]
                fn from(name: &$Name) -> Self {
                    Self(name.0.clone())
                }
            }

            /// Read an erased model name back as this kind of name.
            ///
            /// The kind travels beside the name, so the caller that has already matched the kind
            /// narrows here. This is the only way back from [`ModelName`], and writing it out is
            /// what makes the narrowing reviewable: two unrelated name types still cannot be
            /// interchanged without both conversions appearing in the code.
            impl From<&ModelName> for $Name {
                #[inline]
                fn from(name: &ModelName) -> Self {
                    Self(name.0.clone())
                }
            }
        )+
    };
}

declare_model_names! {
    SchemaName,
    WireSchemaName,
    CodecName,
    ClientName,
    VhostName,
    BranchName,
    EndpointName,
    SignalingProtocolName,
    GeneratorName,
    InferencerName,
    WasmProcessorName,
    IngestorName,
    ReingestorName,
    RelayName,
    LookupName,
    JunctionName,
    DeduplicatorName,
    CorrelatorName,
    ReordererName,
    WindowProcessorName,
    EmitterName,
    PlacementName,
    UdfName,
    ResourceName,
    SubscriptionName,
    UserName,
}

/// A model name is already the erased form, so it widens into itself. This is what lets an API
/// that takes `impl Into<ModelName>` accept both a relay's own name and a name already erased.
impl From<&ModelName> for ModelName {
    #[inline]
    fn from(name: &ModelName) -> Self {
        name.clone()
    }
}

fn validate(raw: &str, dots: DotPolicy) -> Result<String, Report<NameError>> {
    if raw.is_empty() {
        return Err(Report::new(NameError::Empty));
    }

    if raw.len() > MAX_NAME_LEN {
        return Err(Report::new(NameError::TooLong {
            max: MAX_NAME_LEN,
            actual: raw.len(),
        }));
    }

    for ch in raw.chars() {
        if ch == '.' && dots == DotPolicy::Rejected {
            return Err(Report::new(NameError::DotNotAllowed));
        }

        let allowed = ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '~' | '.');
        if !allowed {
            return Err(Report::new(NameError::InvalidChar { ch }));
        }
    }

    Ok(raw.to_ascii_lowercase())
}

#[cfg(test)]
mod tests {
    use indexmap::IndexMap;
    use meticulous::ResultExt as _;

    use super::{DomainName, MAX_NAME_LEN, ModelName, NameError, RelayName, SchemaName};

    #[test]
    fn parse_lowercases_and_display_roundtrips() {
        let relay = RelayName::parse("Orders_Raw").expect("valid relay name");
        assert_eq!(relay.as_str(), "orders_raw");
        assert_eq!(relay.to_string(), "orders_raw");

        let domain = DomainName::parse("Prod").expect("valid domain name");
        assert_eq!(domain.as_str(), "prod");
        assert_eq!(domain.to_string(), "prod");
    }

    #[test]
    fn only_a_domain_rejects_a_dot() {
        let relay = RelayName::parse("topic.main").expect("a relay name allows dots");
        assert_eq!(relay.as_str(), "topic.main");

        let err = DomainName::parse("topic.main").expect_err("a domain name rejects dots");
        assert!(matches!(err.current_context(), NameError::DotNotAllowed));
    }

    #[test]
    fn parse_rejects_invalid_characters() {
        let err = RelayName::parse("bad/slash").expect_err("slash is invalid");
        assert!(matches!(
            err.current_context(),
            NameError::InvalidChar { ch: '/' }
        ));
    }

    #[test]
    fn parse_enforces_the_length_boundary() {
        let max = "a".repeat(MAX_NAME_LEN);
        assert_eq!(
            SchemaName::parse(&max)
                .expect("max length is valid")
                .as_str(),
            max
        );

        let too_long = "a".repeat(MAX_NAME_LEN + 1);
        let err = SchemaName::parse(&too_long).expect_err("must reject too long");
        assert!(matches!(
            err.current_context(),
            NameError::TooLong {
                max: MAX_NAME_LEN,
                actual
            } if *actual == MAX_NAME_LEN + 1
        ));
    }

    #[test]
    fn a_model_name_widens_from_the_name_of_any_model() {
        let relay = RelayName::parse("orders").expect("valid relay name");
        let schema = SchemaName::parse("orders").expect("valid schema name");

        assert_eq!(ModelName::from(&relay), ModelName::from(&schema));
        assert_eq!(ModelName::from(relay).as_str(), "orders");
    }

    #[test]
    fn clones_and_name_widening_share_the_validated_text() {
        let relay = RelayName::parse("orders")
            .assured("the fixed test literal satisfies the relay name grammar");
        let cloned = relay.clone();
        let erased = ModelName::from(&relay);
        let narrowed = RelayName::from(&erased);

        assert!(relay.0.shares_allocation_with(&cloned.0));
        assert!(relay.0.shares_allocation_with(&erased.0));
        assert!(relay.0.shares_allocation_with(&narrowed.0));
    }

    #[test]
    fn names_keep_string_hashing_and_debug_behavior() {
        let relay = RelayName::parse("orders")
            .assured("the fixed test literal satisfies the relay name grammar");
        let mut relays = IndexMap::new();
        relays.insert(relay.clone(), 7_u8);

        assert_eq!(relays.get("orders"), Some(&7));
        assert_eq!(format!("{relay:?}"), "RelayName(\"orders\")");
    }

    #[test]
    fn serde_keeps_names_as_strings() {
        let relay = RelayName::parse("orders")
            .assured("the fixed test literal satisfies the relay name grammar");
        let encoded = serde_json::to_string(&relay)
            .assured("a validated name has an infallible JSON string representation");
        let decoded = serde_json::from_str::<RelayName>(&encoded)
            .verified("the JSON was produced from a relay name immediately above");

        assert_eq!(encoded, r#""orders""#);
        assert_eq!(decoded, relay);
    }

    #[test]
    fn archived_names_roundtrip_through_inline_string_storage() {
        let relay = RelayName::parse("orders")
            .assured("the fixed test literal satisfies the relay name grammar");
        let encoded = rkyv::to_bytes::<rkyv::rancor::Error>(&relay)
            .assured("a validated name has an inline archived string representation");
        let plain = rkyv::to_bytes::<rkyv::rancor::Error>(&relay.as_str().to_owned())
            .assured("a string has an inline archived string representation");
        let decoded = rkyv::from_bytes::<RelayName, rkyv::rancor::Error>(&encoded)
            .verified("the archive was produced from a relay name immediately above");

        assert_eq!(encoded.as_slice(), plain.as_slice());
        assert_eq!(decoded, relay);
    }
}
