[package]
description = "The Syslog source and sink transports and their shared client configuration for Nervix"
edition.workspace = true
license-file.workspace = true
name = "nervix-connector-syslog"
version.workspace = true

[lints]
workspace = true

[features]
default = []
shuttle = [
  "dep:shuttle-tokio",
  "nervix-connector/shuttle",
  "shuttle-tokio/shuttle",
]

[dependencies]
ahash = { workspace = true }
async-trait = { workspace = true }
error-stack = { workspace = true }
meticulous = { workspace = true }
nervix-connector = { workspace = true }
nervix-models = { workspace = true }
nonzero_ext = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
shuttle-tokio = { workspace = true, features = [
  "io-util",
  "macros",
  "net",
  "rt",
  "sync",
], optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "io-util",
  "macros",
  "net",
  "rt",
  "sync",
] }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
