[package]
description = "The ZeroMQ source and sink connector for Nervix"
edition.workspace = true
license-file.workspace = true
name = "nervix-connector-zeromq"
version.workspace = true

[lints]
workspace = true

[features]
default = []
shuttle = ["nervix-connector/shuttle", "nervix-primitives/shuttle"]

[dependencies]
async-trait = { workspace = true }
error-stack = { workspace = true }
nervix-connector = { workspace = true }
nervix-models = { workspace = true }
nervix-primitives = { workspace = true, features = ["native"] }
thiserror = { workspace = true }
zeromq = { workspace = true }
