[package]
description = "The ZeroMQ source and sink connector for Nervix"
edition.workspace = true
license-file.workspace = true
name = "nervix-connector-zeromq"
version.workspace = true

[lints]
workspace = true

[features]
default = []
shuttle = [
  "dep:shuttle-tokio",
  "nervix-connector/shuttle",
  "shuttle-tokio/shuttle",
]

[dependencies]
async-trait = { workspace = true }
error-stack = { workspace = true }
nervix-connector = { workspace = true }
nervix-models = { workspace = true }
shuttle-tokio = { workspace = true, features = ["rt"], optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
zeromq = { workspace = true }
