[package]
description = "The HTTP source and sink connectors for Nervix"
edition.workspace = true
license-file.workspace = true
name = "nervix-connector-http"
version.workspace = true

[lints]
workspace = true

[features]
default = []
shuttle = ["nervix-connector/shuttle", "nervix-primitives/shuttle"]

[dependencies]
async-trait = { workspace = true }
error-stack = { workspace = true }
httparse = { workspace = true }
httpdate = { workspace = true }
nervix-connector = { workspace = true }
nervix-dns = { workspace = true }
nervix-models = { workspace = true }
nervix-primitives = { workspace = true, features = ["native"] }
reqwest = { workspace = true, features = ["rustls"] }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net", "rt", "time"] }
tokio-rustls = { workspace = true }
url = { workspace = true }

[dev-dependencies]
meticulous = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
