// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nervixwasm

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"
)

type ProcessorTypeKind byte

const (
	ProcessorTypeKindU8       ProcessorTypeKind = 0
	ProcessorTypeKindI8       ProcessorTypeKind = 1
	ProcessorTypeKindU16      ProcessorTypeKind = 2
	ProcessorTypeKindI16      ProcessorTypeKind = 3
	ProcessorTypeKindU32      ProcessorTypeKind = 4
	ProcessorTypeKindI32      ProcessorTypeKind = 5
	ProcessorTypeKindU64      ProcessorTypeKind = 6
	ProcessorTypeKindI64      ProcessorTypeKind = 7
	ProcessorTypeKindBool     ProcessorTypeKind = 8
	ProcessorTypeKindString   ProcessorTypeKind = 9
	ProcessorTypeKindDatetime ProcessorTypeKind = 10
	ProcessorTypeKindF32      ProcessorTypeKind = 11
	ProcessorTypeKindF64      ProcessorTypeKind = 12
	ProcessorTypeKindArray    ProcessorTypeKind = 13
	ProcessorTypeKindVec      ProcessorTypeKind = 14
)

var EnumNamesProcessorTypeKind = map[ProcessorTypeKind]string{
	ProcessorTypeKindU8:       "U8",
	ProcessorTypeKindI8:       "I8",
	ProcessorTypeKindU16:      "U16",
	ProcessorTypeKindI16:      "I16",
	ProcessorTypeKindU32:      "U32",
	ProcessorTypeKindI32:      "I32",
	ProcessorTypeKindU64:      "U64",
	ProcessorTypeKindI64:      "I64",
	ProcessorTypeKindBool:     "Bool",
	ProcessorTypeKindString:   "String",
	ProcessorTypeKindDatetime: "Datetime",
	ProcessorTypeKindF32:      "F32",
	ProcessorTypeKindF64:      "F64",
	ProcessorTypeKindArray:    "Array",
	ProcessorTypeKindVec:      "Vec",
}

var EnumValuesProcessorTypeKind = map[string]ProcessorTypeKind{
	"U8":       ProcessorTypeKindU8,
	"I8":       ProcessorTypeKindI8,
	"U16":      ProcessorTypeKindU16,
	"I16":      ProcessorTypeKindI16,
	"U32":      ProcessorTypeKindU32,
	"I32":      ProcessorTypeKindI32,
	"U64":      ProcessorTypeKindU64,
	"I64":      ProcessorTypeKindI64,
	"Bool":     ProcessorTypeKindBool,
	"String":   ProcessorTypeKindString,
	"Datetime": ProcessorTypeKindDatetime,
	"F32":      ProcessorTypeKindF32,
	"F64":      ProcessorTypeKindF64,
	"Array":    ProcessorTypeKindArray,
	"Vec":      ProcessorTypeKindVec,
}

func (v ProcessorTypeKind) String() string {
	if s, ok := EnumNamesProcessorTypeKind[v]; ok {
		return s
	}
	return "ProcessorTypeKind(" + strconv.FormatInt(int64(v), 10) + ")"
}

type ColumnSource byte

const (
	ColumnSourceInput     ColumnSource = 0
	ColumnSourceGenerated ColumnSource = 1
)

var EnumNamesColumnSource = map[ColumnSource]string{
	ColumnSourceInput:     "Input",
	ColumnSourceGenerated: "Generated",
}

var EnumValuesColumnSource = map[string]ColumnSource{
	"Input":     ColumnSourceInput,
	"Generated": ColumnSourceGenerated,
}

func (v ColumnSource) String() string {
	if s, ok := EnumNamesColumnSource[v]; ok {
		return s
	}
	return "ColumnSource(" + strconv.FormatInt(int64(v), 10) + ")"
}

type MessagePayload byte

const (
	MessagePayloadNONE           MessagePayload = 0
	MessagePayloadBranchInit     MessagePayload = 1
	MessagePayloadInputEnvelope  MessagePayload = 2
	MessagePayloadOutputEnvelope MessagePayload = 3
	MessagePayloadGuestSnapshot  MessagePayload = 4
)

var EnumNamesMessagePayload = map[MessagePayload]string{
	MessagePayloadNONE:           "NONE",
	MessagePayloadBranchInit:     "BranchInit",
	MessagePayloadInputEnvelope:  "InputEnvelope",
	MessagePayloadOutputEnvelope: "OutputEnvelope",
	MessagePayloadGuestSnapshot:  "GuestSnapshot",
}

var EnumValuesMessagePayload = map[string]MessagePayload{
	"NONE":           MessagePayloadNONE,
	"BranchInit":     MessagePayloadBranchInit,
	"InputEnvelope":  MessagePayloadInputEnvelope,
	"OutputEnvelope": MessagePayloadOutputEnvelope,
	"GuestSnapshot":  MessagePayloadGuestSnapshot,
}

func (v MessagePayload) String() string {
	if s, ok := EnumNamesMessagePayload[v]; ok {
		return s
	}
	return "MessagePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}

type ProcessorType struct {
	_tab flatbuffers.Table
}

func GetRootAsProcessorType(buf []byte, offset flatbuffers.UOffsetT) *ProcessorType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProcessorType{}
	x.Init(buf, n+offset)
	return x
}

func FinishProcessorTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProcessorType(buf []byte, offset flatbuffers.UOffsetT) *ProcessorType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProcessorType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProcessorTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProcessorType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProcessorType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProcessorType) Kind() ProcessorTypeKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ProcessorTypeKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ProcessorType) MutateKind(n ProcessorTypeKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ProcessorType) Element(obj *ProcessorType) *ProcessorType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ProcessorType)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ProcessorType) ArrayLen() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProcessorType) MutateArrayLen(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func ProcessorTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ProcessorTypeAddKind(builder *flatbuffers.Builder, kind ProcessorTypeKind) {
	builder.PrependByteSlot(0, byte(kind), 0)
}
func ProcessorTypeAddElement(builder *flatbuffers.Builder, element flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(element), 0)
}
func ProcessorTypeAddArrayLen(builder *flatbuffers.Builder, arrayLen uint32) {
	builder.PrependUint32Slot(2, arrayLen, 0)
}
func ProcessorTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type ProcessorField struct {
	_tab flatbuffers.Table
}

func GetRootAsProcessorField(buf []byte, offset flatbuffers.UOffsetT) *ProcessorField {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProcessorField{}
	x.Init(buf, n+offset)
	return x
}

func FinishProcessorFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProcessorField(buf []byte, offset flatbuffers.UOffsetT) *ProcessorField {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProcessorField{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProcessorFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProcessorField) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProcessorField) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProcessorField) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProcessorField) Type(obj *ProcessorType) *ProcessorType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ProcessorType)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ProcessorField) Optional() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ProcessorField) MutateOptional(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func ProcessorFieldStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ProcessorFieldAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ProcessorFieldAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(type_), 0)
}
func ProcessorFieldAddOptional(builder *flatbuffers.Builder, optional bool) {
	builder.PrependBoolSlot(2, optional, false)
}
func ProcessorFieldEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type ProcessorSchema struct {
	_tab flatbuffers.Table
}

func GetRootAsProcessorSchema(buf []byte, offset flatbuffers.UOffsetT) *ProcessorSchema {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProcessorSchema{}
	x.Init(buf, n+offset)
	return x
}

func FinishProcessorSchemaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProcessorSchema(buf []byte, offset flatbuffers.UOffsetT) *ProcessorSchema {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProcessorSchema{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProcessorSchemaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProcessorSchema) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProcessorSchema) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProcessorSchema) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProcessorSchema) Fields(obj *ProcessorField, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ProcessorSchema) FieldsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ProcessorSchemaStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ProcessorSchemaAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ProcessorSchemaAddFields(builder *flatbuffers.Builder, fields flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(fields), 0)
}
func ProcessorSchemaStartFieldsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ProcessorSchemaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type BranchInit struct {
	_tab flatbuffers.Table
}

func GetRootAsBranchInit(buf []byte, offset flatbuffers.UOffsetT) *BranchInit {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BranchInit{}
	x.Init(buf, n+offset)
	return x
}

func FinishBranchInitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBranchInit(buf []byte, offset flatbuffers.UOffsetT) *BranchInit {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BranchInit{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBranchInitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BranchInit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BranchInit) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BranchInit) DomainName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BranchInit) DomainType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BranchInit) BranchKey(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BranchInit) BranchKeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BranchInit) BranchKeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BranchInit) MutateBranchKey(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BranchInit) InputSchema(obj *ProcessorSchema) *ProcessorSchema {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ProcessorSchema)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *BranchInit) OutputSchemas(obj *ProcessorSchema, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BranchInit) OutputSchemasLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BranchInitStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func BranchInitAddDomainName(builder *flatbuffers.Builder, domainName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(domainName), 0)
}
func BranchInitAddDomainType(builder *flatbuffers.Builder, domainType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(domainType), 0)
}
func BranchInitAddBranchKey(builder *flatbuffers.Builder, branchKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(branchKey), 0)
}
func BranchInitStartBranchKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BranchInitAddInputSchema(builder *flatbuffers.Builder, inputSchema flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(inputSchema), 0)
}
func BranchInitAddOutputSchemas(builder *flatbuffers.Builder, outputSchemas flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(outputSchemas), 0)
}
func BranchInitStartOutputSchemasVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BranchInitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type OutputRow struct {
	_tab flatbuffers.Table
}

func GetRootAsOutputRow(buf []byte, offset flatbuffers.UOffsetT) *OutputRow {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OutputRow{}
	x.Init(buf, n+offset)
	return x
}

func FinishOutputRowBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOutputRow(buf []byte, offset flatbuffers.UOffsetT) *OutputRow {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OutputRow{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOutputRowBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OutputRow) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OutputRow) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OutputRow) Tokens(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *OutputRow) TokensLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *OutputRow) MutateTokens(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *OutputRow) SourceToken() *uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetUint64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *OutputRow) MutateSourceToken(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func OutputRowStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OutputRowAddTokens(builder *flatbuffers.Builder, tokens flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tokens), 0)
}
func OutputRowStartTokensVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func OutputRowAddSourceToken(builder *flatbuffers.Builder, sourceToken uint64) {
	builder.PrependUint64(sourceToken)
	builder.Slot(1)
}
func OutputRowEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type AckTokenSet struct {
	_tab flatbuffers.Table
}

func GetRootAsAckTokenSet(buf []byte, offset flatbuffers.UOffsetT) *AckTokenSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AckTokenSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishAckTokenSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAckTokenSet(buf []byte, offset flatbuffers.UOffsetT) *AckTokenSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AckTokenSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAckTokenSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AckTokenSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AckTokenSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AckTokenSet) Tokens(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *AckTokenSet) TokensLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AckTokenSet) MutateTokens(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func AckTokenSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AckTokenSetAddTokens(builder *flatbuffers.Builder, tokens flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tokens), 0)
}
func AckTokenSetStartTokensVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func AckTokenSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type NackSet struct {
	_tab flatbuffers.Table
}

func GetRootAsNackSet(buf []byte, offset flatbuffers.UOffsetT) *NackSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NackSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishNackSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNackSet(buf []byte, offset flatbuffers.UOffsetT) *NackSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NackSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNackSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NackSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NackSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NackSet) Tokens(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *NackSet) TokensLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *NackSet) MutateTokens(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *NackSet) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NackSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NackSetAddTokens(builder *flatbuffers.Builder, tokens flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tokens), 0)
}
func NackSetStartTokensVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func NackSetAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reason), 0)
}
func NackSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type MessageErrorSet struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageErrorSet(buf []byte, offset flatbuffers.UOffsetT) *MessageErrorSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageErrorSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageErrorSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageErrorSet(buf []byte, offset flatbuffers.UOffsetT) *MessageErrorSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageErrorSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageErrorSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageErrorSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageErrorSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageErrorSet) Tokens(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *MessageErrorSet) TokensLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MessageErrorSet) MutateTokens(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *MessageErrorSet) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MessageErrorSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MessageErrorSetAddTokens(builder *flatbuffers.Builder, tokens flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tokens), 0)
}
func MessageErrorSetStartTokensVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func MessageErrorSetAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reason), 0)
}
func MessageErrorSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type AckSidecar struct {
	_tab flatbuffers.Table
}

func GetRootAsAckSidecar(buf []byte, offset flatbuffers.UOffsetT) *AckSidecar {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AckSidecar{}
	x.Init(buf, n+offset)
	return x
}

func FinishAckSidecarBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAckSidecar(buf []byte, offset flatbuffers.UOffsetT) *AckSidecar {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AckSidecar{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAckSidecarBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AckSidecar) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AckSidecar) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AckSidecar) Rows(obj *OutputRow, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AckSidecar) RowsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AckSidecar) Acked(obj *AckTokenSet, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AckSidecar) AckedLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AckSidecar) Nacked(obj *NackSet, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AckSidecar) NackedLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AckSidecar) MessageErrors(obj *MessageErrorSet, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AckSidecar) MessageErrorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AckSidecarStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func AckSidecarAddRows(builder *flatbuffers.Builder, rows flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(rows), 0)
}
func AckSidecarStartRowsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AckSidecarAddAcked(builder *flatbuffers.Builder, acked flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(acked), 0)
}
func AckSidecarStartAckedVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AckSidecarAddNacked(builder *flatbuffers.Builder, nacked flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(nacked), 0)
}
func AckSidecarStartNackedVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AckSidecarAddMessageErrors(builder *flatbuffers.Builder, messageErrors flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(messageErrors), 0)
}
func AckSidecarStartMessageErrorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AckSidecarEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type InputEnvelope struct {
	_tab flatbuffers.Table
}

func GetRootAsInputEnvelope(buf []byte, offset flatbuffers.UOffsetT) *InputEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InputEnvelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishInputEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInputEnvelope(buf []byte, offset flatbuffers.UOffsetT) *InputEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InputEnvelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInputEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InputEnvelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InputEnvelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InputEnvelope) ArrowIpcBatch(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *InputEnvelope) ArrowIpcBatchLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *InputEnvelope) ArrowIpcBatchBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InputEnvelope) MutateArrowIpcBatch(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *InputEnvelope) Acks(obj *AckSidecar) *AckSidecar {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(AckSidecar)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func InputEnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func InputEnvelopeAddArrowIpcBatch(builder *flatbuffers.Builder, arrowIpcBatch flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(arrowIpcBatch), 0)
}
func InputEnvelopeStartArrowIpcBatchVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func InputEnvelopeAddAcks(builder *flatbuffers.Builder, acks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(acks), 0)
}
func InputEnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type OutputColumnRef struct {
	_tab flatbuffers.Table
}

func GetRootAsOutputColumnRef(buf []byte, offset flatbuffers.UOffsetT) *OutputColumnRef {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OutputColumnRef{}
	x.Init(buf, n+offset)
	return x
}

func FinishOutputColumnRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOutputColumnRef(buf []byte, offset flatbuffers.UOffsetT) *OutputColumnRef {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OutputColumnRef{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOutputColumnRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OutputColumnRef) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OutputColumnRef) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OutputColumnRef) Source() ColumnSource {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ColumnSource(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OutputColumnRef) MutateSource(n ColumnSource) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *OutputColumnRef) ColumnIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OutputColumnRef) MutateColumnIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func OutputColumnRefStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OutputColumnRefAddSource(builder *flatbuffers.Builder, source ColumnSource) {
	builder.PrependByteSlot(0, byte(source), 0)
}
func OutputColumnRefAddColumnIndex(builder *flatbuffers.Builder, columnIndex uint32) {
	builder.PrependUint32Slot(1, columnIndex, 0)
}
func OutputColumnRefEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type RoutedOutput struct {
	_tab flatbuffers.Table
}

func GetRootAsRoutedOutput(buf []byte, offset flatbuffers.UOffsetT) *RoutedOutput {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RoutedOutput{}
	x.Init(buf, n+offset)
	return x
}

func FinishRoutedOutputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRoutedOutput(buf []byte, offset flatbuffers.UOffsetT) *RoutedOutput {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RoutedOutput{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRoutedOutputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RoutedOutput) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RoutedOutput) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RoutedOutput) OutputRelay() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoutedOutput) Columns(obj *OutputColumnRef, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RoutedOutput) ColumnsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RoutedOutput) Acks(obj *AckSidecar) *AckSidecar {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(AckSidecar)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RoutedOutputStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RoutedOutputAddOutputRelay(builder *flatbuffers.Builder, outputRelay flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(outputRelay), 0)
}
func RoutedOutputAddColumns(builder *flatbuffers.Builder, columns flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(columns), 0)
}
func RoutedOutputStartColumnsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RoutedOutputAddAcks(builder *flatbuffers.Builder, acks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(acks), 0)
}
func RoutedOutputEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type OutputEnvelope struct {
	_tab flatbuffers.Table
}

func GetRootAsOutputEnvelope(buf []byte, offset flatbuffers.UOffsetT) *OutputEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OutputEnvelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishOutputEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOutputEnvelope(buf []byte, offset flatbuffers.UOffsetT) *OutputEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OutputEnvelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOutputEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OutputEnvelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OutputEnvelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OutputEnvelope) GeneratedArrowIpcBatch(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *OutputEnvelope) GeneratedArrowIpcBatchLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *OutputEnvelope) GeneratedArrowIpcBatchBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OutputEnvelope) MutateGeneratedArrowIpcBatch(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *OutputEnvelope) Outputs(obj *RoutedOutput, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *OutputEnvelope) OutputsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func OutputEnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OutputEnvelopeAddGeneratedArrowIpcBatch(builder *flatbuffers.Builder, generatedArrowIpcBatch flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(generatedArrowIpcBatch), 0)
}
func OutputEnvelopeStartGeneratedArrowIpcBatchVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func OutputEnvelopeAddOutputs(builder *flatbuffers.Builder, outputs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(outputs), 0)
}
func OutputEnvelopeStartOutputsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func OutputEnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type GuestSnapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsGuestSnapshot(buf []byte, offset flatbuffers.UOffsetT) *GuestSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GuestSnapshot{}
	x.Init(buf, n+offset)
	return x
}

func FinishGuestSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGuestSnapshot(buf []byte, offset flatbuffers.UOffsetT) *GuestSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GuestSnapshot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGuestSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GuestSnapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GuestSnapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GuestSnapshot) ProcessedBatches() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GuestSnapshot) MutateProcessedBatches(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *GuestSnapshot) ProcessedRows() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GuestSnapshot) MutateProcessedRows(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *GuestSnapshot) PendingStartRow() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GuestSnapshot) MutatePendingStartRow(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *GuestSnapshot) LastDomainTimeNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GuestSnapshot) MutateLastDomainTimeNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *GuestSnapshot) LastTimeoutHandle() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GuestSnapshot) MutateLastTimeoutHandle(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *GuestSnapshot) PendingBatch(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *GuestSnapshot) PendingBatchLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GuestSnapshot) PendingBatchBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GuestSnapshot) MutatePendingBatch(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *GuestSnapshot) InitMetadata(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *GuestSnapshot) InitMetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GuestSnapshot) InitMetadataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GuestSnapshot) MutateInitMetadata(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *GuestSnapshot) SavedState(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *GuestSnapshot) SavedStateLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GuestSnapshot) SavedStateBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GuestSnapshot) MutateSavedState(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *GuestSnapshot) ErrorState() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GuestSnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func GuestSnapshotAddProcessedBatches(builder *flatbuffers.Builder, processedBatches uint64) {
	builder.PrependUint64Slot(0, processedBatches, 0)
}
func GuestSnapshotAddProcessedRows(builder *flatbuffers.Builder, processedRows uint64) {
	builder.PrependUint64Slot(1, processedRows, 0)
}
func GuestSnapshotAddPendingStartRow(builder *flatbuffers.Builder, pendingStartRow uint64) {
	builder.PrependUint64Slot(2, pendingStartRow, 0)
}
func GuestSnapshotAddLastDomainTimeNanos(builder *flatbuffers.Builder, lastDomainTimeNanos int64) {
	builder.PrependInt64Slot(3, lastDomainTimeNanos, 0)
}
func GuestSnapshotAddLastTimeoutHandle(builder *flatbuffers.Builder, lastTimeoutHandle int64) {
	builder.PrependInt64Slot(4, lastTimeoutHandle, 0)
}
func GuestSnapshotAddPendingBatch(builder *flatbuffers.Builder, pendingBatch flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(pendingBatch), 0)
}
func GuestSnapshotStartPendingBatchVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func GuestSnapshotAddInitMetadata(builder *flatbuffers.Builder, initMetadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(initMetadata), 0)
}
func GuestSnapshotStartInitMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func GuestSnapshotAddSavedState(builder *flatbuffers.Builder, savedState flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(savedState), 0)
}
func GuestSnapshotStartSavedStateVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func GuestSnapshotAddErrorState(builder *flatbuffers.Builder, errorState flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(errorState), 0)
}
func GuestSnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type Message struct {
	_tab flatbuffers.Table
}

const MessageIdentifier = "NVWX"

func GetRootAsMessage(buf []byte, offset flatbuffers.UOffsetT) *Message {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Message{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(MessageIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func MessageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, MessageIdentifier)
}

func GetSizePrefixedRootAsMessage(buf []byte, offset flatbuffers.UOffsetT) *Message {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Message{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(MessageIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedMessageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, MessageIdentifier)
}

func (rcv *Message) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Message) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Message) PayloadType() MessagePayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return MessagePayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Message) MutatePayloadType(n MessagePayload) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Message) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func MessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MessageAddPayloadType(builder *flatbuffers.Builder, payloadType MessagePayload) {
	builder.PrependByteSlot(0, byte(payloadType), 0)
}
func MessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func MessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
