# The top-level include defers discovery until upstream has composed its complete graph.
# Only libraries in that graph enter the combined archive; build tools and unrelated targets do not.
if(CMAKE_CROSSCOMPILING AND onnxruntime_USE_CUDA)
  # Upstream finds CUDA dependencies before enabling the language. FindCUDAToolkit's
  # standalone NVCC probe uses host defaults, so discover the target compiler first.
  enable_language(CUDA)
endif()

function(nervix_cuda_abseil)
  # Clang's preprocessor advertises this host builtin, but NVCC's device frontend lacks it.
  # Supply the same NVCC exclusion the pinned Abseil header uses for its other relocation builtin.
  set(source "${abseil_cpp_SOURCE_DIR}/absl/meta/type_traits.h")
  file(READ "${source}" content)
  set(guard "#if ABSL_HAVE_BUILTIN(__builtin_is_cpp_trivially_relocatable)")
  string(FIND "${content}" "${guard}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "The pinned Abseil relocation trait does not match the NVCC patch")
  endif()
  string(REPLACE "${guard}" "${guard} && !defined(__NVCC__)" content "${content}")
  set(headers "${CMAKE_BINARY_DIR}/nervix-cuda-includes")
  file(MAKE_DIRECTORY "${headers}/absl/meta")
  file(CONFIGURE OUTPUT "${headers}/absl/meta/type_traits.h" CONTENT "${content}" @ONLY)

  # Clang also advertises class nullability annotations that NVCC's device frontend cannot parse.
  set(source "${abseil_cpp_SOURCE_DIR}/absl/base/nullability.h")
  file(READ "${source}" content)
  set(guard "ABSL_HAVE_FEATURE(nullability_on_classes)")
  string(FIND "${content}" "${guard}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "The pinned Abseil nullability header does not match the NVCC patch")
  endif()
  string(REPLACE "${guard}" "${guard} && !defined(__NVCC__)" content "${content}")
  file(MAKE_DIRECTORY "${headers}/absl/base")
  file(CONFIGURE OUTPUT "${headers}/absl/base/nullability.h" CONTENT "${content}" @ONLY)

  # NVCC emits lifetimebound annotations in positions that Clang rejects.
  set(source "${abseil_cpp_SOURCE_DIR}/absl/base/attributes.h")
  file(READ "${source}" content)
  set(guard "#if ABSL_HAVE_CPP_ATTRIBUTE(clang::lifetimebound)")
  string(FIND "${content}" "${guard}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "The pinned Abseil lifetime attribute does not match the NVCC patch")
  endif()
  string(REPLACE "${guard}"
    "#if defined(__NVCC__)\n#define ABSL_ATTRIBUTE_LIFETIME_BOUND\n#elif ABSL_HAVE_CPP_ATTRIBUTE(clang::lifetimebound)"
    content "${content}")
  file(CONFIGURE OUTPUT "${headers}/absl/base/attributes.h" CONTENT "${content}" @ONLY)
  target_include_directories(onnxruntime_providers_cuda BEFORE PRIVATE
    "$<$<COMPILE_LANGUAGE:CUDA>:${headers}>")
endfunction()

function(nervix_collect_library name)
  if(NOT TARGET "${name}")
    return()
  endif()
  get_target_property(alias "${name}" ALIASED_TARGET)
  if(alias)
    set(name "${alias}")
  endif()
  get_property(visited GLOBAL PROPERTY NERVIX_VISITED_LIBRARIES)
  if("${name}" IN_LIST visited)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY NERVIX_VISITED_LIBRARIES "${name}")
  get_target_property(kind "${name}" TYPE)
  get_target_property(imported "${name}" IMPORTED)
  if(kind STREQUAL "STATIC_LIBRARY" AND NOT imported)
    set_property(GLOBAL APPEND PROPERTY NERVIX_ARCHIVE_TARGETS "${name}")
  endif()
  foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(dependencies "${name}" "${property}")
    if(NOT dependencies)
      continue()
    endif()
    foreach(dependency IN LISTS dependencies)
      if(dependency MATCHES "^\\$<(LINK_ONLY|BUILD_INTERFACE|BUILD_LOCAL_INTERFACE):(.*)>$")
        set(dependency "${CMAKE_MATCH_2}")
      endif()
      nervix_collect_library("${dependency}")
    endforeach()
  endforeach()
endfunction()

function(nervix_static_artifacts)
  nervix_collect_library(onnxruntime)
  get_property(archives GLOBAL PROPERTY NERVIX_ARCHIVE_TARGETS)
  if(NOT archives)
    message(FATAL_ERROR "The ONNX Runtime graph did not contain static libraries")
  endif()
  set(paths "")
  foreach(archive IN LISTS archives)
    string(APPEND paths "$<TARGET_FILE:${archive}>\n")
  endforeach()
  file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/nervix-archives.txt" CONTENT "${paths}")
  if(onnxruntime_USE_CUDA)
    nervix_cuda_abseil()
    list(APPEND archives onnxruntime_providers_shared onnxruntime_providers_cuda)
  endif()
  add_custom_target(nervix_static_artifacts DEPENDS ${archives})
endfunction()

cmake_language(DEFER CALL nervix_static_artifacts)
