# The top-level include defers discovery until upstream has composed its complete graph.
# Only libraries in that graph enter the combined archive; build tools and unrelated targets do not.
if(CMAKE_CROSSCOMPILING AND onnxruntime_USE_CUDA)
  # Upstream finds CUDA dependencies before enabling the language. FindCUDAToolkit's
  # standalone NVCC probe uses host defaults, so discover the target compiler first.
  enable_language(CUDA)
endif()

function(nervix_llvm_group_query_attention)
  # The member template depends on T; LLVM requires an explicit template disambiguator.
  set(source "${ONNXRUNTIME_ROOT}/contrib_ops/cuda/bert/group_query_attention.cc")
  get_target_property(sources onnxruntime_providers_cuda SOURCES)
  if(NOT "${source}" IN_LIST sources)
    message(FATAL_ERROR "The CUDA provider does not contain group_query_attention.cc")
  endif()
  file(READ "${source}" content)
  set(call "Info().GetAttrOrDefault<int64_t>(\"qk_output\",")
  string(FIND "${content}" "${call}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "The pinned group-query attention source does not match the LLVM patch")
  endif()
  string(REPLACE "${call}" "Info().template GetAttrOrDefault<int64_t>(\"qk_output\"," content "${content}")
  set(patched "${CMAKE_BINARY_DIR}/nervix-group_query_attention.cc")
  file(CONFIGURE OUTPUT "${patched}" CONTENT "${content}" @ONLY)
  list(REMOVE_ITEM sources "${source}")
  list(APPEND sources "${patched}")
  set_property(TARGET onnxruntime_providers_cuda PROPERTY SOURCES "${sources}")
endfunction()

function(nervix_cuda_abseil)
  # Clang's preprocessor advertises this host builtin, but NVCC's device frontend lacks it.
  # Supply the same NVCC exclusion the pinned Abseil header uses for its other relocation builtin.
  set(source "${abseil_cpp_SOURCE_DIR}/absl/meta/type_traits.h")
  file(READ "${source}" content)
  set(guard "#if ABSL_HAVE_BUILTIN(__builtin_is_cpp_trivially_relocatable)")
  string(FIND "${content}" "${guard}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "The pinned Abseil relocation trait does not match the NVCC patch")
  endif()
  string(REPLACE "${guard}" "${guard} && !defined(__NVCC__)" content "${content}")
  set(headers "${CMAKE_BINARY_DIR}/nervix-cuda-includes")
  file(MAKE_DIRECTORY "${headers}/absl/meta")
  file(CONFIGURE OUTPUT "${headers}/absl/meta/type_traits.h" CONTENT "${content}" @ONLY)
  target_include_directories(onnxruntime_providers_cuda BEFORE PRIVATE
    "$<$<COMPILE_LANGUAGE:CUDA>:${headers}>")
endfunction()

function(nervix_collect_library name)
  if(NOT TARGET "${name}")
    return()
  endif()
  get_target_property(alias "${name}" ALIASED_TARGET)
  if(alias)
    set(name "${alias}")
  endif()
  get_property(visited GLOBAL PROPERTY NERVIX_VISITED_LIBRARIES)
  if("${name}" IN_LIST visited)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY NERVIX_VISITED_LIBRARIES "${name}")
  get_target_property(kind "${name}" TYPE)
  get_target_property(imported "${name}" IMPORTED)
  if(kind STREQUAL "STATIC_LIBRARY" AND NOT imported)
    set_property(GLOBAL APPEND PROPERTY NERVIX_ARCHIVE_TARGETS "${name}")
  endif()
  foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(dependencies "${name}" "${property}")
    if(NOT dependencies)
      continue()
    endif()
    foreach(dependency IN LISTS dependencies)
      if(dependency MATCHES "^\\$<(LINK_ONLY|BUILD_INTERFACE|BUILD_LOCAL_INTERFACE):(.*)>$")
        set(dependency "${CMAKE_MATCH_2}")
      endif()
      nervix_collect_library("${dependency}")
    endforeach()
  endforeach()
endfunction()

function(nervix_static_artifacts)
  nervix_collect_library(onnxruntime)
  get_property(archives GLOBAL PROPERTY NERVIX_ARCHIVE_TARGETS)
  if(NOT archives)
    message(FATAL_ERROR "The ONNX Runtime graph did not contain static libraries")
  endif()
  set(paths "")
  foreach(archive IN LISTS archives)
    string(APPEND paths "$<TARGET_FILE:${archive}>\n")
  endforeach()
  file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/nervix-archives.txt" CONTENT "${paths}")
  if(onnxruntime_USE_CUDA)
    nervix_llvm_group_query_attention()
    nervix_cuda_abseil()
    list(APPEND archives onnxruntime_providers_shared onnxruntime_providers_cuda)
  endif()
  add_custom_target(nervix_static_artifacts DEPENDS ${archives})
endfunction()

cmake_language(DEFER CALL nervix_static_artifacts)
