[package]
description = "Asynchronous host name resolution for the connections a Nervix node opens"
edition.workspace = true
license-file.workspace = true
name = "nervix-dns"
version.workspace = true

[lints]
workspace = true

[dependencies]
arch-into = { workspace = true }
aws-smithy-runtime-api = { workspace = true }
error-stack = { workspace = true }
hickory-resolver = { workspace = true }
hyper-util = { workspace = true, features = ["client-legacy", "tokio"] }
indexmap = { workspace = true }
meticulous = { workspace = true }
nervix-primitives = { workspace = true, features = ["native"] }
reqwest = { workspace = true }
reqwest_iceberg = { workspace = true }
resolv-conf = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tower-service = { workspace = true }
tracing = { workspace = true }
triomphe = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper-util = { workspace = true, features = [
  "client-legacy",
  "http1",
  "tokio",
] }
nervix-test-environment = { workspace = true }
rustls = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
] }
webpki-roots = { workspace = true }
