server {
    listen 9325 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/node.pem;
    ssl_certificate_key /etc/nginx/certs/node-key.pem;

    location / {
        proxy_pass http://elasticmq:9324;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}
