[package]
description = "The RabbitMQ sink connector for Nervix"
edition.workspace = true
license-file.workspace = true
name = "nervix-connector-rabbitmq"
version.workspace = true

[lints]
workspace = true

[features]
default = []
shuttle = [
  "dep:shuttle-tokio",
  "nervix-connector/shuttle",
  "shuttle-tokio/shuttle",
]

[dependencies]
async-trait = { workspace = true }
error-stack = { workspace = true }
futures-util = { workspace = true }
humantime = { workspace = true }
lapin = { workspace = true }
meticulous = { workspace = true }
nervix-connector = { workspace = true }
nervix-models = { workspace = true }
shuttle-tokio = { workspace = true, features = [
  "macros",
  "rt",
  "time",
], optional = true }
tokio = { workspace = true, features = ["macros", "rt", "time"] }
